version: "3"

services:
  mail:
    build: .
    # Mail-Go runs in /, and it looks for config in the current dir. Hence /config
    volumes:
      - ./config:/config
    ports:
      # Container 80 -> Host 8080
      - "8080:80"
    # We must wait for the DB to import/etc before starting ourselves.
    depends_on:
      - "database"
    networks:
      - "internal"
  database:
    image: mysql:5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: rc24
      MYSQL_PASSWORD: changeme
    ports:
      # Container 80 -> Host 8080
      - "3306:3306"
    volumes:
      - mail_data:/var/lib/mysql
      - ./schema/:/docker-entrypoint-initdb.d/:ro
    networks:
      - "internal"

volumes:
  mail_data:
networks:
  internal: